/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        try
        {
            User.main(new String[] {});
            assertNotNull("app should have a greeting", "SUCCESSS");

        }
        catch(Exception e)
        {
            assertNotNull("app should have a greeting", e);
        }
    }
}
